- README.md
- [ v ] 문서 / Documentation
* [SEDEVOPS-19](https://hanwhavision.atlassian.net/browse/SEDEVOPS-19)
[SEDEVOPS-19]: https://hanwhavision.atlassian.net/browse/SEDEVOPS-19?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> README.md add

- profile/README.md
> README.md 업데이트

- .github/workflows/create_release.yaml
- .github/workflows/deploy-magic-backend.yaml
- .github/workflows/deploy-magic-frontend.yaml
- .github/workflows/files/matrix-magic-target-repo.json
- .github/workflows/job_datahub_frontend_build.yaml
- .github/workflows/job_magic_backend_build.yaml
- .github/workflows/job_toolbox_frontend_build.yaml
- .github/workflows/static-analysis-manual.yaml
- .github/workflows/static-analysis.yaml
* [KDOG-1762](https://hanwhavision.atlassian.net/browse/KDOG-1762)
* [KDOG-1763](https://hanwhavision.atlassian.net/browse/KDOG-1763)
[KDOG-1762]: https://hanwhavision.atlassian.net/browse/KDOG-1762?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[KDOG-1763]: https://hanwhavision.atlassian.net/browse/KDOG-1763?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add magic cicd

- .github/workflows/job_datahub_frontend_build.yaml
- .github/workflows/job_toolbox_frontend_build.yaml
* [KDOG-1762](https://hanwhavision.atlassian.net/browse/KDOG-1762)
* [KDOG-1763](https://hanwhavision.atlassian.net/browse/KDOG-1763)
[KDOG-1762]: https://hanwhavision.atlassian.net/browse/KDOG-1762?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[KDOG-1763]: https://hanwhavision.atlassian.net/browse/KDOG-1763?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: typo edit

- .github/workflows/deploy-magic-frontend.yaml
- .github/workflows/job_datahub_frontend_build.yaml
- .github/workflows/job_toolbox_frontend_build.yaml
* [KDOG-1762](https://hanwhavision.atlassian.net/browse/KDOG-1762)
* [KDOG-1763](https://hanwhavision.atlassian.net/browse/KDOG-1763)
[KDOG-1762]: https://hanwhavision.atlassian.net/browse/KDOG-1762?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[KDOG-1763]: https://hanwhavision.atlassian.net/browse/KDOG-1763?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: change working dir for toolbox frontned

- .github/workflows/job_datahub_frontend_build.yaml
- .github/workflows/job_magic_backend_build.yaml
- .github/workflows/job_toolbox_frontend_build.yaml
* [KDOG-1827](https://hanwhavision.atlassian.net/browse/KDOG-1827)
[KDOG-1827]: https://hanwhavision.atlassian.net/browse/KDOG-1827?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: update cicd for hotfix jira release

- .github/workflows/create_release.yaml
* [KDOG-1827](https://hanwhavision.atlassian.net/browse/KDOG-1827)
[KDOG-1827]: https://hanwhavision.atlassian.net/browse/KDOG-1827?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: update target branch when create github release note

- .github/workflows/job_datahub_frontend_build.yaml
- .github/workflows/job_magic_backend_build.yaml
- .github/workflows/job_toolbox_frontend_build.yaml
- .github/workflows/static-analysis.yaml
* [KDOG-1827](https://hanwhavision.atlassian.net/browse/KDOG-1827)
[KDOG-1827]: https://hanwhavision.atlassian.net/browse/KDOG-1827?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add condition to seperate qa and prod env processes

- .github/workflows/create_release.yaml
- .github/workflows/job_datahub_frontend_build.yaml
- .github/workflows/job_magic_backend_build.yaml
- .github/workflows/static-analysis.yaml
> chore: typo

- .github/workflows/job_magic_backend_build.yaml
> chore: edit typo for bucket prefix

- .github/workflows/static-analysis.yaml
> feat: update coverity container version update and add coverity report step

- .github/workflows/job_magic_backend_build.yaml
> feat: install dependencies step modification for toolbox backend deployment

- .github/workflows/job_datahub_frontend_build.yaml
- .github/workflows/job_toolbox_frontend_build.yaml
* [OPS-2080](https://hanwhavision.atlassian.net/browse/OPS-2080)
[OPS-2080]: https://hanwhavision.atlassian.net/browse/OPS-2080?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: update frontend cicd process

- .github/workflows/deploy-magic-backend.yaml
- .github/workflows/deploy-magic-frontend.yaml
- .github/workflows/job_datahub_frontend_build.yaml
- .github/workflows/job_toolbox_frontend_build.yaml
* [OPS-2094](https://hanwhavision.atlassian.net/browse/OPS-2094)
[OPS-2094]: https://hanwhavision.atlassian.net/browse/OPS-2094?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: temp prod build for frontend

- .github/workflows/job_magic_backend_build.yaml
* [OPS-2424](https://hanwhavision.atlassian.net/browse/OPS-2424)
[OPS-2424]: https://hanwhavision.atlassian.net/browse/OPS-2424?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: get environment file from s3

- .github/workflows/job_magic_backend_build.yaml
> feat: make simple when get environment file from s3 bucket

- .github/workflows/job_magic_backend_build.yaml
* [OPS-2474](https://hanwhavision.atlassian.net/browse/OPS-2474)
[OPS-2474]: https://hanwhavision.atlassian.net/browse/OPS-2474?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: injecting app version while CICD

- .github/workflows/job_magic_backend_build.yaml
* [OPS-2520](https://hanwhavision.atlassian.net/browse/OPS-2520)
[OPS-2520]: https://hanwhavision.atlassian.net/browse/OPS-2520?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add release version as metadata

- .github/workflows/job_toolbox_frontend_build.yaml
* [OPS-2571](https://hanwhavision.atlassian.net/browse/OPS-2571)
[OPS-2571]: https://hanwhavision.atlassian.net/browse/OPS-2571?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: get env from s3 bucket and no build for prod

- .github/workflows/job_datahub_frontend_build.yaml
- .github/workflows/job_toolbox_frontend_build.yaml
* [OPS-2537](https://hanwhavision.atlassian.net/browse/OPS-2537)
[OPS-2537]: https://hanwhavision.atlassian.net/browse/OPS-2537?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add cicd for frontend rollback system

- .github/workflows/job_datahub_frontend_build.yaml
* [OPS-2572](https://hanwhavision.atlassian.net/browse/OPS-2572)
[OPS-2572]: https://hanwhavision.atlassian.net/browse/OPS-2572?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: datahub get environment from s3 and no build for prod

- .github/workflows/job_magic_backend_build.yaml
> feat: update backend cicd as well

- .github/workflows/job_magic_backend_build.yaml
> feat: add build for qa env

- .github/workflows/job_magic_backend_build.yaml
> feat: modify target env bucket on code deploy script

- .github/workflows/job_datahub_frontend_build.yaml
- .github/workflows/job_magic_backend_build.yaml
- .github/workflows/job_toolbox_frontend_build.yaml
> feat: fix errror

- .github/workflows/job_datahub_frontend_build.yaml
- .github/workflows/job_toolbox_frontend_build.yaml
> feat: change the order of steps

- .github/workflows/job_datahub_frontend_build.yaml
- .github/workflows/job_toolbox_frontend_build.yaml
> feat: update zip path

- .github/workflows/job_magic_backend_build.yaml
> feat: fix npm version

- .github/workflows/create_release.yaml
- .github/workflows/deploy-magic-backend.yaml
- .github/workflows/files/matrix-magic-target-repo.json
- .github/workflows/job_magic_external_backend_build.yaml
* [OPS-3132](https://hanwhavision.atlassian.net/browse/OPS-3132)
[OPS-3132]: https://hanwhavision.atlassian.net/browse/OPS-3132?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> test: add external api instance deployment process

- .github/workflows/create_release.yaml
- .github/workflows/deploy-magic-backend.yaml
- .github/workflows/job_datahub_frontend_build.yaml
* [OPS-3470](https://hanwhavision.atlassian.net/browse/OPS-3470)
[OPS-3470]: https://hanwhavision.atlassian.net/browse/OPS-3470?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OPS-3132-DesignPro-Composing-CICD-for-external-api-instance-for-QA-and-PROD

- .github/workflows/create_release.yaml
> feat: seperate datahub external cicd process from others

- .github/workflows/job_toolbox_frontend_build.yaml
* [OPS-5334](https://hanwhavision.atlassian.net/browse/OPS-5334)
[OPS-5334]: https://hanwhavision.atlassian.net/browse/OPS-5334?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: apply cache control when upload the build file for qa DesignPro environment 

- .github/workflows/job_datahub_frontend_build.yaml
* [OPS-5369](https://hanwhavision.atlassian.net/browse/OPS-5369)
[OPS-5369]: https://hanwhavision.atlassian.net/browse/OPS-5369?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: apply cache control for datahub frontend qa environment

- .github/workflows/job_datahub_frontend_build.yaml
- .github/workflows/job_magic_backend_build.yaml
- .github/workflows/job_toolbox_frontend_build.yaml
* [OPS-6424](https://hanwhavision.atlassian.net/browse/OPS-6424)
[OPS-6424]: https://hanwhavision.atlassian.net/browse/OPS-6424?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: enhancing deployment alert system

- .github/workflows/job_datahub_frontend_build.yaml
- .github/workflows/job_toolbox_frontend_build.yaml
> OPS-5366-DataHub-Modify-the-CICD-process-on-Prod
